import { MenuItem, Review } from './types';

// Static menu data for initial rendering (fallback when Supabase is not configured)
export const menuItems: MenuItem[] = [
  // --- Malaysian Favorites ---
  {
    id: 'malay-1',
    name: 'Nasi Lemak Ayam Goreng',
    description: 'Fragrant coconut rice served with crispy fried chicken, spicy sambal, crunchy anchovies, peanuts, and a hard-boiled egg.',
    price: 12.00,
    category: 'mains',
    image_url: '/images/menu/nasi_lemak.png',
    dietary_tags: ['spicy'],
    available: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'malay-2',
    name: 'Satay (10 Sticks)',
    description: 'Flame-grilled chicken skewers marinated in local spices, served with a rich and chunky peanut sauce, cucumber, and onions.',
    price: 12.00,
    category: 'appetizers',
    image_url: '/images/menu/satay.png',
    dietary_tags: ['gluten-free'],
    available: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'malay-3',
    name: 'Char Kway Teow',
    description: 'Stir-fried flat rice noodles with juicy prawns, cockles, fish cake, and bean sprouts with a smoky breath of the wok.',
    price: 8.50,
    category: 'mains',
    image_url: '/images/menu/char_kway_teow.png',
    dietary_tags: ['spicy'],
    available: true,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'malay-4',
    name: 'Hainanese Chicken Rice',
    description: 'Tender poached chicken served with fragrant ginger-garlic rice, accompanied by a spicy chili dip and savory soup.',
    price: 8.00,
    category: 'mains',
    image_url: '/images/menu/chicken_rice.png',
    dietary_tags: [],
    available: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'malay-5',
    name: 'Roti Canai Kosong',
    description: 'Crispy and flaky hand-flipped flatbread, served with a side of aromatic dhal curry or chicken curry.',
    price: 1.50,
    category: 'appetizers',
    image_url: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=600&h=400&fit=crop',
    dietary_tags: ['vegetarian'],
    available: true,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'malay-6',
    name: 'Curry Laksa',
    description: 'Fragrant spicy coconut curry noodle soup topped with tofu puffs, cockles, prawns, and shredded chicken.',
    price: 9.00,
    category: 'mains',
    image_url: '/images/menu/curry_laksa.png',
    dietary_tags: ['spicy'],
    available: true,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'malay-7',
    name: 'Ramly Burger Special',
    description: 'A Malaysian street food icon — beef or chicken patty wrapped in a thin egg omelet, loaded with black pepper sauce and mayo.',
    price: 6.50,
    category: 'mains',
    image_url: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=600&h=400&fit=crop',
    dietary_tags: [],
    available: true,
    featured: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'malay-8',
    name: 'Cendol',
    description: 'Refreshing shaved ice dessert with green rice flour jelly, creamy coconut milk, and rich Gula Melaka (palm sugar) syrup.',
    price: 7.50,
    category: 'desserts',
    image_url: '/images/menu/cendol.png',
    dietary_tags: ['vegetarian', 'gluten-free'],
    available: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'malay-9',
    name: 'Teh Tarik',
    description: 'Famous Malaysian "pulled" milk tea, frothed to perfection for a smooth, creamy texture and bold flavor.',
    price: 3.50,
    category: 'drinks',
    image_url: '/images/menu/teh_tarik.png',
    dietary_tags: ['vegetarian'],
    available: true,
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'malay-10',
    name: 'Kopi O Coffee',
    description: 'Traditional Malaysian black coffee, roasted with sugar and margarine for a deep, robust aroma.',
    price: 3.00,
    category: 'drinks',
    image_url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&h=400&fit=crop',
    dietary_tags: ['vegan', 'gluten-free'],
    available: true,
    featured: false,
    created_at: new Date().toISOString(),
  },
];

export const reviews: Review[] = [
  {
    id: 'rev-1',
    user_id: 'anon',
    rating: 5,
    comment: 'The Nasi Lemak here is the real deal! The sambal has the perfect kick and the chicken is incredibly crispy. Best Teh Tarik in town.',
    author_name: 'Ahmad S.',
    created_at: '2026-03-15T20:00:00Z',
  },
  {
    id: 'rev-2',
    user_id: 'anon',
    rating: 5,
    comment: 'Reminds me of home. The Satay peanut sauce is so rich and authentic. Definitely order the Cendol for dessert!',
    author_name: 'Mei Ling',
    created_at: '2026-03-20T19:00:00Z',
  },
  {
    id: 'rev-3',
    user_id: 'anon',
    rating: 4,
    comment: 'Love the Char Kway Teow! It has that smoky wok breath. Great service and beautiful vibe.',
    author_name: 'Rajkumar K.',
    created_at: '2026-04-01T21:00:00Z',
  },
];

export const operatingHours = {
  monday: { open: '10:00', close: '22:00' },
  tuesday: { open: '10:00', close: '22:00' },
  wednesday: { open: '10:00', close: '22:00' },
  thursday: { open: '10:00', close: '23:00' },
  friday: { open: '10:00', close: '23:30' },
  saturday: { open: '09:00', close: '23:30' },
  sunday: { open: '09:00', close: '22:00' },
};

export const restaurantInfo = {
  name: 'DineSync Malay',
  tagline: 'Authentic Flavors of Malaysia',
  description: 'A culinary journey through the heart of Malaysia. We bring you the most beloved street food classics and heritage dishes, prepared with authentic spices and traditional techniques.',
  address: 'No. 12, Jalan Telawi 5, Bangsar',
  city: 'Kuala Lumpur, 59100',
  phone: '+60 3-2284 3111',
  email: 'hello@dinesync.my',
  instagram: '@dinesync.my',
};

export const demoReservations = [
  { id: 'res-1', name: 'Zahirul Azim', party: 4, date: '2026-04-24', time: '19:30', status: 'confirmed' },
  { id: 'res-2', name: 'Sarah Johnson', party: 2, date: '2026-04-24', time: '20:00', status: 'pending' },
  { id: 'res-3', name: 'Dato\' Sri Hamzah', party: 8, date: '2026-04-25', time: '20:30', status: 'confirmed' },
];
